export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const INITIALIZE_INGREDIENTS = 'INITIALIZE_INGREDIENTS';
export const ERROR_INGREDIENTS = 'ERROR_INGREDIENTS';
