export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const INITIALIZE_INGREDIENTS = 'INITIALIZE_INGREDIENTS';
export const ERROR_INGREDIENTS = 'ERROR_INGREDIENTS';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const INITIALIZE_ORDERS_START = 'INITIALIZE_ORDERS_START';
export const INITIALIZE_ORDERS_SUCCESS = 'INITIALIZE_ORDERS_SUCCESS';
export const INITIALIZE_ORDERS_FAIL = 'INITIALIZE_ORDERS_FAIL';

export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_SUCCEED = 'AUTH_LOGOUT_SUCCEED';
export const AUTH_CHANGE_REDIRECT_PATH = 'AUTH_CHANGE_REDIRECT_PATH';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
